apiVersion: v1
kind: Service
metadata:
  name: dev-my-app
spec:
  ports:
  - nodePort: 30007
    port: 80
    targetPort: 8080
  selector:
    app: my-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: my-app:dev
        imagePullPolicy: IfNotPresent
        name: my-app
        ports:
        - containerPort: 8080
