FROM python:{{ python_version }}-alpine3.22
RUN apk add --no-cache build-base cargo
COPY --from=ghcr.io/astral-sh/uv:0.8.9 /uv /uvx /bin/

# Copy the project into the image
COPY . /app

# Sync the project into a new environment, asserting the lockfile is up to date
WORKDIR /app
RUN uv sync --locked
