tests:
	@echo "Running tests..."
	uv run pytest --cov={{project_name}} --cov-report=xml --cov-report=html

lint:
	@echo "Running linters..."
	uv run ruff check {{project_name}} tests

format:
	@echo "Formatting code..."
	uv run ruff format {{project_name}} tests

ty:
	@echo "Type checking..."
	uv run ty check {{project_name}}

clean:
	@echo "Cleaning up..."
	rm -rf .pytest_cache .coverage htmlcov coverage.xml

docs:
	@echo "Building documentation..."
	uv run mkdocs build -f docs/mkdocs.yaml

docs_live:
	@echo "Building documentation..."
	uv run mkdocs build -f docs/mkdocs.yaml
	uv run mkdocs serve -f docs/mkdocs.yaml

install:
    @echo "Installing env..."
	uv pip install ."[tools]"
	uv pip install .